services:
  - type: web
    name: my-proxy-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -w 4
    envVars:
      - key: DEBUG_MODE
        value: false
      - key: PORT
        value: 10000
